version: '3'
services:
  reverseproxy:
    image: nginx:1.12.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
  backend1:
    image: jamesdbloom/mockserver
    ports:
      - "1081:11111"
    entrypoint: /opt/mockserver/run_mockserver.sh -serverPort 11111
  backend2:
    image: jamesdbloom/mockserver
    ports:
      - "1082:22222"
    entrypoint: /opt/mockserver/run_mockserver.sh -serverPort 22222
